### ISSUE TITLE
Region free cart works only if cart is already inserted when Home Menu boots up

### ISSUE THREAD

**Issue by aorin-sound** [chaoskagami/corbenik#36] opened 2016-09-05 13:27 UTC
When you insert a foreign region cart, the cursor moves to the cart slot, but no icon appears. 
Booting the home menu with a cart inserted works. 
jpn o3ds, latest fw

**Comment by chaoskagami** [comment] 2016-09-05 13:37
I can't reproduce this.

I have multiple japanese carts and using the same procedure on a US 3DS, it is impossible to reproduce at least for me. The patch is identical to how Luma performs it, so I see no possible way for this to happen.

Unless someone speaks up and confirms this is indeed a thing, I'll be closing it.

**Comment by aorin-sound** [comment] 2016-09-05 13:39
We'd need someone else with a jpn console; this works as it should on my eu n3ds

**Comment by gnmmarechal** [comment] 2016-09-05 14:46
I might have an out-of-region cart, if I can find it I'll give it a shot. I'm EU tho.

**Comment by chaoskagami** [comment] 2016-09-05 15:27
So something to do with JPN firmware...? That's strange.

Can you reproduce the issue with Luma, out of curiousity?

**Comment by chaoskagami** [comment] 2016-09-07 10:31
Bumping to ask once more; can you reproduce the issue on Luma, and is this still an issue?

**Comment by chaoskagami** [comment] 2016-09-08 18:00
Closing issue; @udemiko apparently can't repro on the latest commit. Possible there's some reason behind this, but we may never know.

**Closed as completed by chaoskagami** 2016-09-08 18:00 UTC
