### ISSUE TITLE
TWLoader crashes always

### ISSUE THREAD

**Issue by ghost** [chaoskagami/corbenik#54] opened 2017-01-12 05:21 UTC
I know that TWLoader is in development, but it works in other CFW, but not in this one.
Also test it with the "TWL Patches" on and off.

The logs I do not see much of use since they only log the information of boot by what I understand, but I leave them.

[logs.zip](https://github.com/chaoskagami/corbenik/files/700748/logs.zip)

**Comment by chaoskagami** [comment] 2017-01-12 07:04
Did you install the TWLNAND side as the instructions state to do? TWLoader is composed of the 3DS frontend and nds-bootstrap.

TWL Patches must be "on" for it to work, as well.

**Comment by ghost** [comment] 2017-01-13 02:33
Yes, install the 2 cia that brings the release of the twloader and the folders of this are as it is necessary to put them.

PS: I recorded a video, https://www.youtube.com/watch?v=4X3069nalNc

**Comment by chaoskagami** [comment] 2017-01-13 04:35
That's...pretty freaking weird.

I'll look into it, but this might be hell and a half to debug.

Do unsigned DSiware games and (if available) flashcarts work?

**Comment by ghost** [comment] 2017-01-13 20:14
The unsigned dsiware games work, unfortunately I do not have a flashcard...

**Comment by chaoskagami** [comment] 2017-01-14 06:11
Would you mind sharing the configuration file for SM64:DS? Obviously *not* the rom - I can dump that from my own cart for testing.

**Comment by ghost** [comment] 2017-01-18 04:27
No idea how to get the "configuration".
PD: I downloaded the rom here -yarrharr-

**Comment by ghost** [comment] 2017-01-18 06:05
I did test a flashcard on the nightly, it worked fine...

**Comment by chaoskagami** [comment] 2017-01-18 12:05
What part of "obviously _not_ the rom" was unclear? No links to piracy sites here.

That aside, I can't reproduce with a flashcart or booting retail games via TWLoader, so I guess it's something to do with the patching / hypervisor if this isn't a misconfiguration.

**Comment by chaoskagami** [comment] 2017-01-18 13:02
I'm unable to reproduce this.

I did not test with SM64 specifically, but a few games marked as working as well as not working. Bomberman appears to boot (and save!) and a few other games whitescreen, but no 'error has occured' ever occurs.

**Comment by ghost** [comment] 2017-02-11 16:29
I'm not exactly an expert in TWLoader and friends, but maybe it's because your firmlaunch hook is disabled? (it's visible @ 0:24 in your video)

And "unsigned DSiWare games" != "pirated/sideloaded DSiWare games". Try with *any* improperly signed DSi homebrew installed on your 3DS and it should crash the same way as TWLoader.

**Comment by chaoskagami** [comment] 2017-02-11 22:14
Nice catch @Wolfvak, I missed that completely. Video logs are...annoying, from a bug report perspective.

If signature patches for TWL are disabled, but on for native firm, the system will firmlaunch but subsequently fail the signature check and abort (error has occured.)

This behavior is certainly consistent with an unpatched TWL / firmlaunch disabled TWL.

Anyways, new policy. "Video" logs will now result in merciless closing of bug reports immediately. It's just too much of a hassle to deal with. I don't have enough time in my day to replay thirty second videos thirty times to figure out what it says.

I'll close this in the morning.

On February 11, 2017 11:29:12 AM EST, Wolfvak <notifications@github.com> wrote:
>I'm not exactly an expert in TWLoader and friends, but maybe it's
>because your firmlaunch hook is disabled? (it's visible @ 0:24 in your
>video)
>
>And "unsigned DSiWare games" != "pirated/sideloaded DSiWare games". Try
>with *any* DSi homebrew installed on your 3DS and it should crash the
>same way as TWLoader.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/chaoskagami/corbenik/issues/54#issuecomment-279157407

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed as completed** 2017-02-12 10:14 UTC
Labels: PEBKAC, cannot-reproduce
