### ISSUE TITLE
Sorry guys

### ISSUE THREAD

**Issue by ToadillerYT22** [chaoskagami/corbenik#80] opened 2017-09-05 15:30 UTC
Guys I am so sorry I guess I was just so desperate I couldn't help it. I have been through a lot more hardships than you know at my school. By the way, let me explain the brick.

First of all, It was at night and I was not near a computer so I could not boot into the firmware because I dont think Corbenik CFW Updater got all the files. Just FYI, I tried to install Corbenik, nothing happened so I installed skeith... So I tried to remove Corbenik by disabling everything, which, I know, was really, really stupid of me.. Only to find it got some sort of soft-brick and it only showed Luma3DS chainloader screen just one last time then it wouldn't load at all.. So I tried MagnetHAX to fix it and only to find that it just made it worse. Now whenever I have a SD Card in and i press the power button it just turns off in about less than a second. Luma3DS still wouldn't boot and whenever I took the SD Card out it would show, of course, the (arg= 0) error i think its called and I was wondering if a Hardmod would fix it?

And please dont ban me again, I have thought about what I have done wrong and I promise to be nice now to you guys and help as much as I can with this project!

**Comment by ToadillerYT22** [comment] 2017-09-05 15:33
By the way, what do I do on my 3DS once I compile Corbenik on my SD Card?

**Comment by ghost** [comment] 2017-09-06 18:26
That is, if I fix it hopefully..

**Comment by gnmmarechal** [comment] 2017-09-06 20:31
The original corbenik updater is broken and was replaced by another one I wrote, and it cannot, ever, cause any bricks. It only modifies SD card files. As such, it was not caused by that. That I can say with certainty.

**Comment by chaoskagami** [comment] 2017-09-07 11:04
FYI, the updater isn't official and it isn't created by me; the only officially supported(?) install method is manual unzip/copy/fetch. @gnmmarechal has broken shit multiple times without noticing. :)

I wasn't the one who reported you and deleted the issues. I'm unsure who did. In fact, I find it unsettling that github would just nuke everything out of existence for a ban. What if an initial issue report was valid, but the user was subsequently banned for something else, etc.

Long and short of it; corbenik doesn't really work anymore on boot9-based setups. Since I've stopped development, all I can say is there are known issues and I'm not going to be fixing them. If you want something with better customer support, you should probably use Luma. To be honest, I personally don't even use my own project anymore (sadly.) It's far too much effort.

You'll also probably have in general better luck asking in the general questions topic on GBAtemp; the issue tracker here is for well, issues. Not user support, but bug reports and known misbehavior in the software.

The fact that you came here and maturely apologized makes me feel much better. So long as you realize what you did wrong, I'll just let the past be the past.

To be frank Toad: I'm sympathetic towards going through hell in school. My entire school years were spent being bullied for being "different" by other students AND teachers, also combined with the fact that I had some of the best grades so school was exceedingly boring from an educational perspective. I ended up getting a GED and enrolling straight in college before hitting the same garbage and quitting again.

That said: stress is never an excuse to take out frustration on others.

I'll leave this open for now in case anyone else wants to help you out, but keep in mind you probably won't recieve the same level of help here as on a forum.

**Comment by ToadillerYT22** [comment] 2017-09-07 16:18
:) thank you guys have a awesome day!

**Comment by gnmmarechal** [comment] 2017-09-07 19:31
@chaoskagami , tbh, I only made the updater to make it a bit easier for me, and didn't bother fixing a lot of stuff since it did work for me.

**Comment by chaoskagami** [comment] 2017-09-08 13:20
Eh, it's hard to account for every single possible misuse in existence. Things happen. Don't worry about it~

**Comment by Derek1199** [comment] 2017-09-29 06:22
@ToadillerYT22 what happened is you're not bricked. All you need is to place luma's boot.firm on your SD card. Easy fix. As for bricking, @chaoskagami is right. You wouldn't brick from that. The only possible way you could brick is updating with firm protection disabled, that's highly unlikely though. It would likely take you back to stock firmware if you did that. Since updates write the Native_Firm to firm0 and firm1.(only firm0 is ever used usually) But you would be able to easily fix this by reinstalling b9s if this were to occur. So yeah.

**Comment by gnmmarechal** [comment] 2017-09-29 18:27
@Derek1199 iirc, it would be fine if the console was one of the Old 3DS family. As far as I'm aware, updating a New 3DS console without FIRM protection would brick it.

**Comment by fox8091** [comment] 2017-09-30 06:14
With A9LH, sure. But with B9S? No.

**Comment by gnmmarechal** [comment] 2017-09-30 13:25
Yes, I was talking about A9LH.

**Comment by Derek1199** [comment] 2017-09-30 18:17
I was talking about B9S. But yeah, Corbenik isn't really suitable for Boot9 setups. It has issues. Like for example screeninit is broken on n3ds.

**Comment by ghost** [comment] 2017-10-06 20:43
OMG THANK YOU SO MUCH Derek1199 I mean that very sincerely.

**Comment by ghost** [comment] 2017-10-06 20:57
HOLY MOTHER OF DUCK IT WORKED THANKS!!! :+1:  :)

**Comment by chaoskagami** [comment] 2017-10-08 15:10
Since you seem to have resolved your issue, I'm going to go ahead and close this issue now. I'm glad you fixed it.

**Closed as completed by chaoskagami** 2017-10-08 15:10 UTC
