### ISSUE TITLE
Module: injected /skeith/lib/module/native/loader.cxi hang

### ISSUE THREAD

**Issue by gnmmarechal** [chaoskagami/corbenik#38] opened 2016-10-15 22:24 UTC
I'm running the latest Skeith, it writes 

Module: injected /skeith/lib/module/native/loader.cxi

then hangs.

**Comment by chaoskagami** [comment] 2016-10-15 23:58
I'm aware. A new Skeith build hasn't been pushed yet (can do), but this was already identified and fixed by https://github.com/chaoskagami/corbenik/commit/d7df9971d0dcae8a1724d9af0c6d625260143250

I really recommend running the stable for now. There's a few unresolved issues in master I'm still trying to identify the cause of.

**Closed as completed by chaoskagami** 2016-10-15 23:58 UTC

**Comment by gnmmarechal** [comment] 2016-10-16 01:33
I knew I read somewhere that you'd fixed this somewhere. Anyway, is there any reason why "Info" was removed? I do remember sometimes I had issues regarding the FIRM that caused it to hang, but I'd assumed that was my own fault.

**Comment by chaoskagami** [comment] 2016-10-16 15:39
There were many issues in the old code; I ended up merging the refactor (partially) earlier than I would have liked. Technically, the "info" wasn't removed, the entire handling of FIRM was gutted and almost 90% reimplemented.

I only _partially_ fixed the issues; the firmlaunch failed thing is next up. At least it doesn't outright hang now...

I really feel this bears saying, for the Nth time: people should use the freaking stable builds. Git is not necessarily expected to work. I commit changes publically as I finish them.

On October 15, 2016 9:33:48 PM EDT, "Mário Alexandre Lopes Liberato" notifications@github.com wrote:

> I knew I read somewhere that you'd fixed this somewhere. Anyway, is
> there any reason why "Info" was removed? I do remember sometimes I had
> issues regarding the FIRM that caused it to hang, but I'd assumed that
> was my own fault.
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/chaoskagami/corbenik/issues/38#issuecomment-254021631

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
